name: task_planner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  timezone: ^0.9.2
  flutter_svg: ^2.0.7
  flutter_timezone: ^1.0.7
  table_calendar: ^3.0.8
  dartz: null
  mobx: null
  flutter_mobx: null
  get_it: null
  flutter_dotenv: null
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  synchronized: ^3.1.0
  flutter_local_notifications: null
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sembast
      version: '>=0.1.0'
  tekartik_app_flutter_sqflite:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      path: app_sqflite
      ref: dart2_3
      version: '>=0.4.2'
  lottie: ^2.4.0
  flutter_datetime_picker_plus: ^2.0.1
  collection: ^1.17.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  mobx_codegen: null
  json_serializable: null
  flutter_lints: ^2.0.2
  lint: null
  flutter_launcher_icons: ^0.13.1
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/
    - assets/animations/
    - assets/images/
flutter_intl:
  enabled: true
